### ISSUE TITLE
Inconsistent Problems Arise When Installing New Version of Tethys

### ISSUE THREAD

**Issue by swainn** [tethysplatform/tethys#504]

**Comment by swainn** [comment]
* Script installation doesn't work in Ubuntu unless you override tethys_home or the conda environment name
* Installing with script with environment name that isn't tethys-dev it won't work.
* Import issues on startup with development server
    * Django can't be found
    * Plotly import issues
* Import issues are resolved when using `manage.py runserver --noreload`

**Comment by sdc50** [comment]
> * Script installation doesn't work in Ubuntu unless you override tethys_home or the conda environment name

I've found a solution for this issue. It is caused because the `install_tethys.sh` abuses the `readlink` command on linux to resolve relative paths. This doesn't work when the parent directory of the path doesn't exist. Thus it worked when `tethys_home` was `~/tethys`, but not when it is `~/.tethys/tethys-dev` (if ~/.tethys hasn't already been created). The solution for this is to use method that was used for Mac OS on all systems. This makes the assumption that `python` is in the `PATH`.

**Comment by sdc50** [comment]
> * Installing with script with environment name that isn't tethys-dev it won't work.

This isn't exactly accurate from my experience. I sometimes get the errors with the conda package and sometimes with the script installation, and sometimes with some installations, but not others. I still cannot seem to consistently reproduce this error.

**Comment by swainn** [comment]
> > * Script installation doesn't work in Ubuntu unless you override tethys_home or the conda environment name
> 
> I've found a solution for this issue. It is caused because the `install_tethys.sh` abuses the `readlink` command on linux to resolve relative paths. This doesn't work when the parent directory of the path doesn't exist. Thus it worked when `tethys_home` was `~/tethys`, but not when it is `~/.tethys/tethys-dev` (if ~/.tethys hasn't already been created). The solution for this is to use method that was used for Mac OS on all systems. This makes the assumption that `python` is in the `PATH`.

@sdc50 do you have the solution implemented? Perhaps submit in a PR?

**Comment by swainn** [comment]
@sdc50 so the issue is that with newer linux distributions (like Ubuntu 18.04) python is not installed as python, but python3? So when the script tries to resolve paths using python, it can't?

**Comment by sdc50** [comment]
> @sdc50 do you have the solution implemented? Perhaps submit in a PR?

This was included with #507.



> the issue is that with newer linux distributions (like Ubuntu 18.04) python is not installed as python, but python3? So when the script tries to resolve paths using python, it can't?

The way that I get around this is:

```
sudo ln -s /usr/bin/python3 /usr/bin/python
```
It seems like this should be there by default. However, since it's not great to require users to create the symbolic link I will investigate trying to determine if `python` exists and use `python3` if not.

**Comment by sdc50** [comment]
I've been testing this issue with Ubuntu 16 and CentOS 7. I can't reproduce the error in CentOS, and it only occurs in Ubuntu with the conda package. Previously it seemed like it would only happen with the script install. The inconsistent behavior is baffling. 😕

**Comment by swainn** [comment]
I spent some time looking at the install issue last night. I did several tests from a fresh Ubuntu 18.04 install with both the script and the conda package. These are my observations:

From Fresh VM (I used snapshots, so in theory each test started with the same conditions):

| Script / Conda | Environment Name | Tethys Home | Working?|
---------------------|----------------------------|-------------------|--------------|
| Script  | tethys-dev | .tethys/tethys-dev  | No   |
| Script  | tethys-dev | .tethys/tethys-dev  | No   |
| Script  | tethys-dev | .tethys/tethys-dev  | No   |
| Script  | tethys        | .tethys                    | Yes |
| Script  | hilda          | .tethys/hilda           | No   |
| Conda | tethys        | .tethys/tethys-dev  | Yes |
| Conda | tethys        | .tethys                   | No   |
| Conda | tethys        | .tethys                   | Yes |
| Conda | hilda          | .tethys/hilda          | No   |

Observations:
- I tried installing from the script using the default options and I never got it to work.
- When I used the environment name ``tethys`` with the script (``-n tethys``) it worked.
- The conda package installation is inconsistent. The first time with the default environment name it failed, the second time it succeeded.
- The environment name ``tethys-dev`` worked the first time with the conda installation method
- I tried an environment name other than ``tethys`` or ``tethys-dev`` with both installation methods (``hilda``-- something that I know isn't in the code base) and neither worked.

Todo:

- I took snapshots of each result and I intend to take a closer look at the environments and compare those that failed with those that didn't.
- I need to try the conda environment scenarios again to see if they are consistent.

**Comment by sdc50** [comment]
I'm fairly confident that this is some kind of race condition. That would explain some of the inconsistencies, and is also consistent with the fact that I've been able to "fix" any of the broken environments that I've created by putting in a `time.sleep` statement in the Django module where the errors originate.  

I still don't understand why there is a race condition and why it is manifesting itself where it is, but I've been able to prevent it by adding in an additional import statement in `tethys_gizmos/templatetags/tethys_gizmos.py`. 

```
import plotly  # noqa: F401                   <- This import statement was added
from plotly.offline.offline import get_plotlyjs
from tethys_apps.harvester import SingletonHarvester
```

I'm interested if this will fix others' environments that have the same issue.
